### PR TITLE
Rails 4 support

### LINKED ISSUE #174: /authorization_rules no method error - Rails 3.2.11
NoMethodError in Authorization_rules#index

Showing /home/redvel2/.rvm/gems/ruby-1.9.3-p374@tsp/gems/declarative_authorization-0.5.7/app/views/authorization_rules/index.html.erb where line #16 raised:

undefined method `shift' for :authorization_rules:Symbol

Extracted source (around line #16):

16: <%= policy_analysis_hints(syntax_highlight(h(@auth_rules_script)), @auth_rules_script) %>

### LINKED ISSUE #184: Fedena Installation Error
I am trying to install fedena on my machine , I have the correct version of ruby and gems when i try to run rake fedena:plugins:install_all it does't work, any help with this ?

➜  fedena-v2.3-bundle-linux git:(master) ✗ rake fedena:plugins:install_all
(in /home/dexter/Apps/fedena-v2.3-bundle-linux)
rake aborted!
uninitialized constant Authorization

(See full trace by running task with --trace)
➜  fedena-v2.3-bundle-linux git:(master) ✗ rake fedena:plugins:install_all --trace
(in /home/dexter/Apps/fedena-v2.3-bundle-linux)
*\* Invoke fedena:plugins:install_all (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
uninitialized constant Authorization
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:443:in `load_missing_constant'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in`const_missing'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:92:in `const_missing'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/declarative_authorization-0.5.1/config/routes.rb:5
/home/dexter/Apps/fedena-v2.3-bundle-linux/vendor/plugins/fckeditor/init.rb:27:in`draw'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:226:in `draw_without_fckeditor'
/home/dexter/Apps/fedena-v2.3-bundle-linux/vendor/plugins/fckeditor/init.rb:23:in`draw'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/declarative_authorization-0.5.1/config/routes.rb:4
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load_without_new_constant_marking'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:286:in `load_routes!'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:286:in`each'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:286:in `load_routes!'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:266:in`reload!'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing.rb:381:in `inflections'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/core_ext/object/misc.rb:39:in`returning'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/actionpack-2.3.5/lib/action_controller/routing.rb:380:in `inflections'
/home/dexter/Apps/fedena-v2.3-bundle-linux/config/initializers/inflections.rb:5
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:622:in`load_application_initializers'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:621:in `each'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:621:in`load_application_initializers'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:176:in `process'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:113:in`send'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
/home/dexter/Apps/fedena-v2.3-bundle-linux/config/environment.rb:6
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rails-2.3.5/lib/tasks/misc.rake:4
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/home/dexter/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:604:in`each'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:596:in`invoke_with_call_chain'
/home/dexter/.rvm/rubies/ruby-1.8.7-p302/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/gems/rake-0.8.7/bin/rake:31
/home/dexter/.rvm/gems/ruby-1.8.7-p302/bin/rake:19:in `load'
/home/dexter/.rvm/gems/ruby-1.8.7-p302/bin/rake:19
/home/dexter/.rvm/gems/ruby-1.8.7-p302/bin/ruby_noexec_wrapper:14

### LINKED ISSUE #185: undefined method `shift' for :authorization_rules:Symbol
Hi, when I try to execute http://localhost:3000/authorization_rules I've got the error:

"undefined method `shift' for :authorization_rules:Symbol" 

NoMethodError - undefined method `shift' for :authorization_rules:Symbol:
  declarative_authorization (0.5.7) lib/declarative_authorization/development_support/analyzer.rb:212:in`process_call'

I'm using Rails 4.0.0 and Ruby 1.9.3

### LINKED ISSUE #193: Authorization::AuthorizationUsageError with ActiveRecord::Associations::CollectionProxy
Seems like in rails > 4.0.2 where is ActiveRecord::Associations::CollectionProxy we have issue with authorization (with rails rails ~ 3.2 all is fine)

Message: 

```
Authorization::AuthorizationUsageError: Error occurred while validating
attribute #user on #<ActiveRecord::Associations::CollectionProxy[]>: 
undefined method `user' for #<ActiveRecord::Associations::CollectionProxy[]>. 

Please check your authorization rules and ensure the attribute is correctly
spelled and corresponds to a method on the model you are authorizing for.
```

Rule like:
`if_attribute :object => {:collection => {:user  => is { user } }}`

In Requirements i found `Rails >= 2.2, including 3 ..` are you planing support rails 4?

### PR DESCRIPTION
**Pull request by viacommits**
### Main Changes:
- Updates test suite for Rails 4.0 and 4.1
- Adds route compatibility for Rails 4
- Adds gemfiles for Rails 4.0, 4.1
- Updates analyzer (tests pass, no more no method `shift' error): closes #174 and closes #185, should also fix #193
- Remove deprecated link_to_function and button_to_function from from development support
- Removes deprecated `unloadable` method
- Strong Parameters support: closes #184
- Removes deprecated `scoped` method in favor of `all`, `where(nil)`, and finder methods such as `joins`
- Handles eager loading in Rails 4 with `references` method
- Add Minitest aliases for forward compatibility with Rails > 4.1 test suite
### Todo / Issues
- Polymorphic associations don't quite work in if_attribute
- #193 probably not truly fixed after all
- Nested resources have broken create action
### All tests passing on:
- Rails 2.3.18 (Ruby 1.8.7-p374) :white_check_mark:
- Rails 3.0.20 (Ruby 1.9.3-p484) :white_check_mark:
- Rails 3.1.12 (Ruby 1.9.3-p484) :white_check_mark:
- Rails 3.2.16 (Ruby 1.9.3-p484) :white_check_mark:
- Rails 4.0.2 (Ruby 2.1.2) :white_check_mark:
- Rails 4.1.4 (Ruby 2.1.2) :white_check_mark:

For strong_parameters, I added a `:strong_parameters` option to `filter_resource_access` that accepts a boolean.  It defaults to try on rails > 4 and false on rails < 4.  When `:strong_parameters` is enabled, declarative_authorization **will not** create a new object or set an instance variable for the `create` action because strong_parameters's use of a private method to sanitize parameters expects that the object will be created in the original controller.  This patch will, however, create an empty object for the instance variable of `new` actions.

You can see in the commit history that I initially used @gordonbisnor's fix which involved simply permitting all parameters for all `filter_resource_access` controllers.  It was clean and it worked, but I ended up deciding that this was a too large a vulnerability and removed the fix.  The best way to handle strong_parameters and in RESTful controllers with declarative_authorization is to simply use the Rails default method, which looks something like this:

``` ruby
def create
    @person = Person.new(person_params)
    respond_to do |format|
        if @person.save
            format.html { redirect_to @post, notice: 'Person was successfully created.' }
            format.json { render :show, status: :created, location: @person }
        else
            format.html { render :new }
            format.json { render json: @person.errors, status: :unprocessable_entity }
        end
    end
end

private
def person_params
    params.require(:person).permit(:name, :age)
end
```

:exclamation:**IMPORTANT NOTE**:exclamation:
After switching rubies with RVM, Rails 4.1 returns 3 failures: `HelperTest#test_has_role_with_guest_user`, `AuthorizationTest#test_default_role`, and `AuthorizationTest#test_guest_user`.  Raking a second time (no changes) returns only one failure: `HelperTest#test_has_role_with_guest_user`.  After that, all tests pass, then it alternates between that one failure and all passing.  Does anyone know what might be causing this?  I'm marking Rails 4.1.4 as passing since my best guess is that it's a problem with the test suite.

I also recommend a version bump, possibly to 0.6.0?

### CODE REVIEW

**Comment by gordonbisnor** [comment]
Yeah I did not pull request my changes, was just a personal fork. They were intended only for an internal project. Not sure if there is a GitHub protocol to indicate that beyond not pull requesting. Thanks for this work!

**Comment by mbhnyc** [comment]
What's the status on this? Need these changes to get a migration to 4.1 to pass.  I'm hopping on your branch @zeiv for now!!

**Comment by maletor** [comment]
ping @stffn.

**Comment by viacommits** [comment]
@mbhnyc this patch is ready to merge, in my eyes.  It's in @stffn's hands now. :wink: He's pretty busy though, so feel free to use my fork for the time being.  Also see my `1.0.0` branch, I'll be adding more features to that until this pull request is merged.

**Comment by mbhnyc** [comment]
Thanks @zeiv for providing the bridge code we need

**Comment by maletor** [comment]
I've tried out this patch, but I'm getting an error that wasn't present before.

```
 Failure/Error: post :read, id: id
 ActiveRecord::HasManyThroughCantAssociateThroughHasOneOrManyReflection:
   Cannot modify association 'Conversation#members' because the source reflection class 'Member' is associated to 'Message' via :has_many.
```

Using:

``` ruby
if_attribute members: { receiver: is { user } }
```

Abridged trace:

```
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/through_association.rb:76:in `ensure_mutable'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/through_association.rb:40:in `construct_join_attributes'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/has_many_through_association.rb:149:in `delete_records'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:493:in `remove_records'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:486:in `block in delete_or_destroy'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:152:in `block in transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/transactions.rb:209:in `transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:151:in `transaction'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:486:in `delete_or_destroy'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_association.rb:236:in `delete'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.8/lib/active_record/associations/collection_proxy.rb:566:in `delete'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:630:in `object_attribute_value'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:516:in `block in validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `each'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `all?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:525:in `block in validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `each'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `all?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:515:in `validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:453:in `block in validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:451:in `each'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:451:in `any?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:451:in `validate?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:187:in `block in permit!'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:186:in `each'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/authorization.rb:186:in `permit!'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/in_controller.rb:662:in `permit!'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/in_controller.rb:113:in `block in filter_access_filter'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/in_controller.rb:113:in `each'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/in_controller.rb:113:in `all?'
     # /Users/maletor/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/declarative_authorization-f09effc03599/lib/declarative_authorization/in_controller.rb:113:in `filter_access_filter'
```

Could be because receiver is polymorphic?

**Comment by viacommits** [comment]
Hi @maletor, would you be able to post the relevant associations?  I'm guessing part of it is something like:

``` ruby
class Message < ActiveRecord::Base
  belongs_to :members
  has_many :conversations
end

class Member < ActiveRecord::Base
  has_many :messages
  has_many :conversations, :through => :messages  
end

class Conversation < ActiveRecord::Base
  has_many :messages
  has_many :members, :through => :messages
end
```

But you mentioned it was polymorphic, and a `Receiver` class?

**Comment by maletor** [comment]
Hoping to get around to this at some point. Probably will be next week.
Haven't forgot.

**Comment by cschoene** [comment]
Thanks zeiv, I really appreciate You effort on this !
There  appears to be a small issue when using filter_resource_access with the :nested_in option:
Declarative Authorization tries to load an object via :id for create actions (of the nested type that is to be created, not the parent), which doesn't make any sense.
This occurs for the create action of every nested resource in my project since switching from 0.5.7 to  
https://github.com/zeiv/declarative_authorization, regardless of whether the nesting is one or two levels deep.

**Comment by viacommits** [comment]
Hmm okay.  It looks like I may have broken something with my "fix" to #193... I doubt I'll be able to look at it today, though.  Hopefully over the weekend.  Thanks for the feedback, everyone!

**Comment by maletor** [comment]
Experiencing the following error:

```
Failure/Error: get :index, id: group.id
ActiveRecord::AssociationTypeMismatch:
  Member(#70100856788920) expected, got NilClass(#70100740822840)
```

```
(byebug) current_user.id
1

(byebug) @post.group.members
#<ActiveRecord::Associations::CollectionProxy []>
```

```
filter_access_to [:index, :create], attribute_check: true, load_method: :new_post
```

```
if_attribute group: { members: { user_id: is { user.id } } }
```

Any ideas?

**Comment by aepstein** [comment]
Working off of this fix, I believe I have fixed #193 .  Not sure how is best, but suggest you pull in changes from my rails4 branch.  Also fixed issue reported above by @maletor .  Added back the test associated with this problem with additional assertion for @maletor case.

**Comment by maletor** [comment]
Hi @aepstein, 

We ran our gigantic 4,000 test suite against your branch and everything is green.

So I'd say it's looking good as far as our above 2 concerns and #193.

**Pull request merged**
